run:
  skip-dirs:
    - api
linters:
  enable:
    - containedctx
    - contextcheck
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - forcetypeassert
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gomnd
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused
    - vet
    - wrapcheck
linters-settings:
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID"] # AllowList
  goimports:
    local-prefixes: github.com/msharbaji/grpc-go-example
  wrapcheck:
    ignoreSigRegexps:
      - '.*github.com/msharbaji/grpc-go-example/.*'
    ignorePackageGlobs:
      - google.golang.org/grpc/status
      - github.com/msharbaji/grpc-go-example/*
  gocyclo:
    min-complexity: 12
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - dot
      - prefix(github.com/msharbaji) # other msharbaji modules/ packages
      - prefix(github.com/msharbaji/grpc-go-example)
    custom-order: true