name: Continuous Integration
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Go
        uses: actions/setup-go@v4
      - name: download dependencies
        if: steps.setup-go.outputs.cache-hit != 'true'
        shell: bash
        run: |
          go get -t ./...
      - name: go fmt
        shell: bash
        run: |
          test -z $(gofmt -l .)
      - name: go fmt-diff
        shell: bash
        run: |
          gofmt -e -d .
      - name: go vet
        if: success() || failure()
        shell: bash
        run: |
          go vet ./...
      - name: golangci-lint
        if: success() || failure()
        shell: bash
        run: |
          golangci-lint run --timeout 5m
        with:
          skip-pkg-cache: true
          args: --timeout=1m
      - name: go test
        run: go test ./...
